[project]
name = "yoda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.1",
    "jinja2>=3.1.6",
    "sse-starlette>=3.0.3",
    "uvicorn>=0.38.0",
    "websockets>=15.0.1",
]
